trigger:
- feature/test-branch  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: '<your-acr-name>'
  imageName: 'react-app'

steps:
# Step 1: Login to Azure
- task: AzureCLI@2
  inputs:
    azureSubscription: '<your-service-connection>'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials --resource-group <your-resource-group> --name <your-aks-cluster-name>

# Step 2: Build Docker Image
- script: |
    docker build -t $(acrName).azurecr.io/$(imageName):$(Build.BuildId) .
  displayName: 'Build Docker Image'

# Step 3: Push Docker Image to ACR
- script: |
    az acr login --name $(acrName)
    docker push $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
  displayName: 'Push Docker Image to ACR'

# Step 4: Deploy to Kubernetes
- script: |
    kubectl apply -f k8s/deployment.yaml
    kubectl apply -f k8s/service.yaml
  displayName: 'Deploy to Kubernetes'