name: Deploy Infrastructure and App

on:
  push:
    branches:
      - dev
      - test
      - main
  workflow_dispatch: # Allow manual triggering of this workflow

    
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ github.ref_name }} # Automatically gets branch name (e.g., dev)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Set Environment Variables
        run: |
          if [[ "${{ env.ENVIRONMENT }}" == "dev" ]]; then
            echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
            echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          elif [[ "${{ env.ENVIRONMENT }}" == "test" ]]; then
            echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID_TEST }}" >> $GITHUB_ENV
            echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID_TEST }}" >> $GITHUB_ENV
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID_TEST }}" >> $GITHUB_ENV
            echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET_TEST }}" >> $GITHUB_ENV
          elif [[ "${{ env.ENVIRONMENT }}" == "main" ]]; then
            echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID_MAIN }}" >> $GITHUB_ENV
            echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID_MAIN }}" >> $GITHUB_ENV
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID_MAIN }}" >> $GITHUB_ENV
            echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET_MAIN }}" >> $GITHUB_ENV
          fi

      - name: Azure CLI Login
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra # Ensure Terraform runs in the correct directory

      - name: Import Existing Resource Group
        run: terraform import azurerm_resource_group.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-dev-subscriptionservice
        working-directory: ./infra # Ensure Terraform runs in the correct directory

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "environment=${{ env.ENVIRONMENT }}"
        working-directory: ./infra # Ensure Terraform runs in the correct directory

      - name: Deploy Application to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: subservappservice-${{ env.ENVIRONMENT }} # App name with dynamic environment
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}